# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.8

branches:
  only:
    - master

# http://docs.travis-ci.com/user/languages/go/#Dependency-Management
install:
   - go get github.com/go-redis/redis
   - go get github.com/stretchr/testify

before_install:
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci -ignore examples/simple.go,examples/memory.go,examples/server.go,examples/multi-bucket.go

# http://docs.travis-ci.com/user/database-setup/#Redis
services:
  - redis-server

after_success:
  - coveralls