# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.8

branches:
  only:
    - master

# http://docs.travis-ci.com/user/languages/go/#Dependency-Management
install:
   - go get github.com/gorilla/mux
   - go get github.com/go-redis/redis
   - go get github.com/bsm/redis-lock
   - go get github.com/stretchr/testify

script: go test

# http://docs.travis-ci.com/user/database-setup/#Redis
services:
  - redis-server